
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Heart, Star, Trophy, Users, BookOpen, Target, Zap, Shield } from "lucide-react";
import { Link } from "react-router-dom";
import heroImage from "@/assets/hero-image.jpg";

const LandingPage = () => {
  const features = [
    {
      icon: <Heart className="w-8 h-8" />,
      title: "Character Building",
      description: "Develop respect, empathy, responsibility, and core values through engaging activities.",
      color: "text-red-500"
    },
    {
      icon: <Target className="w-8 h-8" />,
      title: "Life Skills",
      description: "Master emotional intelligence, communication, and decision-making abilities.",
      color: "text-blue-500"
    },
    {
      icon: <Trophy className="w-8 h-8" />,
      title: "Achievement System",
      description: "Earn badges, maintain streaks, and celebrate milestones in your learning journey.",
      color: "text-yellow-500"
    },
    {
      icon: <Users className="w-8 h-8" />,
      title: "Family Oversight",
      description: "Parents can track progress, customize content, and guide their child's development.",
      color: "text-green-500"
    },
    {
      icon: <BookOpen className="w-8 h-8" />,
      title: "Interactive Learning",
      description: "Role-play simulations, quizzes, and storytelling make learning engaging and memorable.",
      color: "text-purple-500"
    },
    {
      icon: <Zap className="w-8 h-8" />,
      title: "AI-Powered",
      description: "Personalized learning paths and custom courses generated by advanced AI technology.",
      color: "text-orange-500"
    }
  ];

  const ageGroups = [
    {
      title: "Foundational (Ages 10-12)",
      description: "Character Values, Basic Life Skills, Confidence & Communication",
      highlights: ["Respect & Empathy", "Money Basics", "Listening Skills"]
    },
    {
      title: "Growth Stage (Ages 13-15)",
      description: "Integrity, Time Management, Public Speaking, Financial Literacy",
      highlights: ["Peer Pressure", "Budgeting", "Self-Discipline"]
    },
    {
      title: "Purpose Stage (Ages 16-18)",
      description: "Leadership, Advanced Life Skills, Entrepreneurship, Life Design",
      highlights: ["Life Purpose", "Advanced Finance", "Goal Setting"]
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-hero">
      {/* Navigation */}
      <nav className="container mx-auto px-6 py-4 flex justify-between items-center">
        <div className="flex items-center space-x-3">
          <img 
            src="/lovable-uploads/06a3ec1d-2039-4b9a-bc9c-fb56fc8266d7.png" 
            alt="ENTETEYE Logo" 
            className="w-24 h-24"
          />
          <span className="text-2xl font-bold gradient-text">ENTETEYE</span>
        </div>
        <div className="space-x-4">
          <Link to="/login">
            <Button variant="outline" size="sm">Login</Button>
          </Link>
          <Link to="/signup">
            <Button variant="hero" size="sm">Get Started</Button>
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="container mx-auto px-6 py-16 text-center">
        <div className="max-w-4xl mx-auto">
          <Badge className="mb-6 achievement-badge">
            <Star className="w-4 h-4 mr-1" />
            Trusted by 10,000+ families
          </Badge>
          
          <h1 className="text-5xl md:text-7xl font-bold mb-6 gradient-text animate-slide-up">
            Build Character,<br />
            Shape Futures
          </h1>
          
          <p className="text-xl md:text-2xl text-muted-foreground mb-8 max-w-3xl mx-auto">
            An engaging e-learning platform that teaches character-building, life skills, and family values to children aged 10-18, with full parental oversight and AI-powered personalization.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
            <Button variant="hero" size="xl" className="animate-bounce-in">
              <Shield className="w-5 h-5 mr-2" />
              Start Free Trial
            </Button>
            <Button variant="outline" size="xl">
              <BookOpen className="w-5 h-5 mr-2" />
              Explore Courses
            </Button>
          </div>
          
          {/* Demo Access */}
          <div className="mb-12">
            <p className="text-lg text-muted-foreground mb-4">Try our demo dashboards:</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/parent-dashboard">
                <Button variant="secondary" size="lg">
                  <Users className="w-5 h-5 mr-2" />
                  Parent Dashboard Demo
                </Button>
              </Link>
              <Link to="/child-dashboard">
                <Button variant="accent" size="lg">
                  <Heart className="w-5 h-5 mr-2" />
                  Child Dashboard Demo
                </Button>
              </Link>
              <Link to="/course-player">
                <Button variant="success" size="lg">
                  <BookOpen className="w-5 h-5 mr-2" />
                  Course Player Demo
                </Button>
              </Link>
            </div>
          </div>
          
          <div className="rounded-2xl overflow-hidden shadow-2xl mx-auto max-w-4xl">
            <img 
              src={heroImage} 
              alt="Children learning character building and life skills"
              className="w-full h-auto"
            />
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="container mx-auto px-6 py-16">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4 gradient-text">Why Choose ENTETEYE?</h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Combining the best of gamified learning with proven character development methodologies.
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <Card key={index} className="card-hover border-0 bg-white/80 backdrop-blur-sm">
              <CardHeader className="text-center">
                <div className={`mx-auto mb-4 ${feature.color}`}>
                  {feature.icon}
                </div>
                <CardTitle className="text-xl">{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-center text-base">
                  {feature.description}
                </CardDescription>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Age-Based Learning */}
      <section className="container mx-auto px-6 py-16">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4 gradient-text">Age-Appropriate Learning Paths</h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Carefully crafted curricula that grow with your child's development and maturity level.
          </p>
        </div>
        
        <div className="grid md:grid-cols-3 gap-8">
          {ageGroups.map((group, index) => (
            <Card key={index} className="card-hover border-0 bg-gradient-to-br from-white via-white to-primary/5">
              <CardHeader>
                <CardTitle className="text-xl text-primary">{group.title}</CardTitle>
                <CardDescription className="text-base">{group.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {group.highlights.map((highlight, idx) => (
                    <Badge key={idx} variant="secondary" className="mr-2 mb-2">
                      {highlight}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-6 py-16">
        <Card className="border-0 bg-gradient-primary text-white shadow-2xl">
          <CardContent className="text-center py-16">
            <h2 className="text-4xl font-bold mb-4">Ready to Start Your Child's Journey?</h2>
            <p className="text-xl mb-8 opacity-90 max-w-2xl mx-auto">
              Join thousands of families who are building character and shaping futures with ENTETEYE.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button variant="secondary" size="xl">
                <Heart className="w-5 h-5 mr-2" />
                Start 14-Day Free Trial
              </Button>
              <Button variant="outline" size="xl" className="border-white text-white hover:bg-white hover:text-primary">
                Schedule Demo
              </Button>
            </div>
          </CardContent>
        </Card>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/50 py-8">
        <div className="container mx-auto px-6 text-center text-muted-foreground">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <img 
              src="/lovable-uploads/06a3ec1d-2039-4b9a-bc9c-fb56fc8266d7.png" 
              alt="ENTETEYE Logo" 
              className="w-20 h-20"
            />
            <span className="text-xl font-bold gradient-text">ENTETEYE</span>
          </div>
          <p>© 2024 ENTETEYE. Building character, shaping futures.</p>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
